String apikey = "YOUR_API_KEY";
List<String> categories = [
    'business',
    'entertainment',
    'general',
    'health',
    'science',
    'sports',
    'technology'
  ];

  List<Map<String, String>> countryCode = [
    {'country': 'United Arab Emirates', 'code': 'ae'},
    {'country': 'Argentina', 'code': 'ar'},
    {'country': 'Austria', 'code': 'at'},
    {'country': 'Australia', 'code': 'au'},
    {'country': 'Belgium', 'code': 'be'},
    {'country': 'Bulgaria', 'code': 'bg'},
    {'country': 'Brazil', 'code': 'br'},
    {'country': 'Canada', 'code': 'ca'},
    {'country': 'Switzerland', 'code': 'ch'},
    {'country': 'China', 'code': 'cn'},
    {'country': 'Colombia', 'code': 'co'},
    {'country': 'Cuba', 'code': 'cu'},
    {'country': 'Czech Republic', 'code': 'cz'},
    {'country': 'Germany', 'code': 'de'},
    {'country': 'Egypt', 'code': 'eg'},
    {'country': 'France', 'code': 'fr'},
    {'country': 'United Kingdom', 'code': 'gb'},
    {'country': 'Greece', 'code': 'gr'},
    {'country': 'Hong Kong', 'code': 'hk'},
    {'country': 'Hungary', 'code': 'hu'},
    {'country': 'Indonesia', 'code': 'id'},
    {'country': 'Ireland', 'code': 'ie'},
    {'country': 'Israel', 'code': 'il'},
    {'country': 'India', 'code': 'in'},
    {'country': 'Italy', 'code': 'it'},
    {'country': 'Japan', 'code': 'jp'},
    {'country': 'South Korea', 'code': 'kr'},
    {'country': 'Lithuania', 'code': 'lt'},
    {'country': 'Latvia', 'code': 'lv'},
    {'country': 'Morocco', 'code': 'ma'},
    {'country': 'Mexico', 'code': 'mx'},
    {'country': 'Malaysia', 'code': 'my'},
    {'country': 'Nigeria', 'code': 'ng'},
    {'country': 'Netherlands', 'code': 'nl'},
    {'country': 'Norway', 'code': 'no'},
    {'country': 'New Zealand', 'code': 'nz'},
    {'country': 'Philippines', 'code': 'ph'},
    {'country': 'Poland', 'code': 'pl'},
    {'country': 'Portugal', 'code': 'pt'},
    {'country': 'Romania', 'code': 'ro'},
    {'country': 'Serbia', 'code': 'rs'},
    {'country': 'Russia', 'code': 'ru'},
    {'country': 'Saudi Arabia', 'code': 'sa'},
    {'country': 'Sweden', 'code': 'se'},
    {'country': 'Singapore', 'code': 'sg'},
    {'country': 'Slovenia', 'code': 'si'},
    {'country': 'Slovakia', 'code': 'sk'},
    {'country': 'Thailand', 'code': 'th'},
    {'country': 'Turkey', 'code': 'tr'},
    {'country': 'Taiwan', 'code': 'tw'},
    {'country': 'Ukraine', 'code': 'ua'},
    {'country': 'United States', 'code': 'us'},
    {'country': 'Venezuela', 'code': 've'},
    {'country': 'South Africa', 'code': 'za'},
  ];